"""SQLAlchemy declarative base with a stable constraint-naming convention.

A consistent naming convention is what makes Alembic migrations
*reversible*: without it, autogenerated DROP statements can't find the
constraint they're meant to remove. The convention below is the
SQLAlchemy-recommended one and must not change without a migration
that renames every constraint accordingly.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for all ORM models in the Control Plane."""

    metadata = metadata
